### ISSUE TITLE
entries don't always appear in search if search term is alias of protein name

### ISSUE THREAD

**Issue by ec363** [tlambert03/FPbase#193]
Some proteins appear not to be searchable by their aliases. Most are, so I'm not sure why a few are not.

Examples: amilRFP and amilCFP. They both have alternate primary names (amilFP593 and amilFP490 respectively) but their entries don't come up if you use "amilRFP" "amilCFP" in the search bar. (They do seem to come up if you click 'Advanced search'.)

**Comment by tlambert03** [comment]
i tweaked the ranking algorithm on for the search results.  "amilRFP" gives 32 hits for names that are similar, but it looks like "exactness" wasn't influencing the sorting strongly enough for it to beat out the fact that it's an alias.  The change is in place now and both of those come up first.  Do let me know though if you feel like it's negatively impacted the result ordering in any other way
