### ISSUE TITLE
Export vector graphics curve

### ISSUE THREAD

**Issue by shalinshah1993** [tlambert03/FPbase#75]
I love using the online tool FPbase Spectra Viewer to visualize the microscope configuration however I couldn't export a high-quality vector graphic (SVG). Does that feature exists or is it in pipeline?

**Comment by tlambert03** [comment]
Thanks Shalin, still pipeline… Turned out to bit a bit harder than I anticipated, so for now I’m afraid the only way to get a perfect copy of what you see on the site is a humble screenshot.  Definitely something I’d like to add though, so thanks for the "vote".

**Comment by tlambert03** [comment]
long time coming... but finally got around to rewriting the spectra viewer.  It now includes the ability to export the current chart as SVG, PDF, or PNG (click the "share" icon at the bottom right of the viewer).  You can also save the state of the current chart as a URL for later recall.

if you have a chance to try it and have any more requests/suggestsions, let me know.
