### ISSUE TITLE
Efficiency calculation not refreshing upon changing laser line or custom filter position

### ISSUE THREAD

**Issue by kdmarchuk** [tlambert03/FPbase#84]
Hi Talley, 

FPbase is extremely cool. 

We have a Leica SP8 with a tunable WLL. I'm using FPbase as a starting guide to image an 8 color panel. I noticed that if you slide the laser excitation or a custom filter around, the efficiency calculation is not updated from the "initial" viewing. As you can see below, the calculation is based upon the filter being located near the emission peak, not where it's currently located. Perhaps a "Refresh Efficient Calculation" button is needed?

Thanks for all your hard work,
Kyle

![FPbaseSpectra](https://user-images.githubusercontent.com/54245002/71131968-10035700-21ab-11ea-852a-cad1b36d3b14.png)

**Comment by tlambert03** [comment]
ahhh, thanks catching that!  will take a look soon

**Comment by tlambert03** [comment]
just pushed a fix.  Will probably finish building and be live in about 15-20 mins.  When you eventually try it out, let me know if you still have any issues.

**Comment by kdmarchuk** [comment]
Thanks for working on this so quickly. Just did a brief test on my end, and it seems like everything is working as expected.

Thanks!
